//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirpProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DEPENDENTE
    {
        public int id_dependente { get; set; }
        public string nm_dependente { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public Nullable<int> id_funcionario { get; set; }
    
        public virtual T_FUNCIONARIO T_FUNCIONARIO { get; set; }
    }
}
