//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirpProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_FUNCIONARIO()
        {
            this.T_DEPENDENTE = new HashSet<T_DEPENDENTE>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public System.DateTime dt_nascimento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DEPENDENTE> T_DEPENDENTE { get; set; }
    }
}
