//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirpProject1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfirpProjectDBEntities : DbContext
    {
        public ConfirpProjectDBEntities()
            : base("name=ConfirpProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_DEPENDENTE> T_DEPENDENTE { get; set; }
        public virtual DbSet<T_FUNCIONARIO> T_FUNCIONARIO { get; set; }
    }
}
